# 不要かも。
version: '3.9'
services:
  db:
    image: mysql:8.0.13
    volumes:
      - db:/var/lib/db
      - ./_init_sql:/docker-entrypoint-initdb.d
    container_name: rust-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $DATABASE_MYSQL_DBNAME
      MYSQL_USER: $DATABASE_MYSQL_USER
      MYSQL_PASSWORD: $DATABASE_MYSQL_PASSWORD
      TZ: $DATABASE_MYSQL_TIMEZONE

volumes:
  db: